# Generated by cucumber-sinatra. (2013-12-06 12:47:04 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'github_api.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = RepoLanguage

class RepoLanguageWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  RepoLanguageWorld.new
end
